version: "3.1"
services:
  spring-boot-docker:
    image: lfallo1/springbootstarter:2.0
    restart: "no"
    ports:
      - "8080:8080"
    links:
      - mailcatcher
      - adminserver
    depends_on:
      - mailcatcher
      - adminserver
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manage/health"]
      interval: 30s
      timeout: 20s
      retries: 3
  postgres:
    build: .
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
  mailcatcher:
    image: tophfr/mailcatcher
    restart: always
    ports:
      - "1080:80"
      - "1025:25"
  adminserver:
    image: lfallo1/springbootadminserver:1.0
    restart: always
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: docker      