version: "3.1"
services:
  spring-boot-docker:
    image: lfallo1/springbootstarter:0.0.1-SNAPSHOT
    restart: "no"
    ports:
      - "8080:8080"
      - "8888:8888"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manage/health"]
      interval: 30s
      timeout: 20s
      retries: 3
  postgres:
    build: .
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin